articles/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # localhost:8080/
    url(r'^$',views.index,name='index'),
    # /localhost:8080/article/article_id
    url(r'^article/(?P<article>[\w-]+)/', views.article, name='article'),
    url(r'^search/', views.search, name='search'),
    # /localhost:8080/categories/category_name
    url(r'^categories/(?P<category>[\w-]+)/', views.articles,name='articles')
]

website/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static

admin.site_title = "Espace d'Administration"
admin.site_header = "Gestion des Articles et des Commentaires"
admin.index_title = ""


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^/', include('articles.urls')),
    url(r'^categories/^', include('articles.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^',include('articles.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from tinymce import HTMLField
from django.core.urlresolvers import resolve

# Create your models here.

def validate_file_extension(value):
    import os
    from django.core.exceptions import ValidationError
    ext = os.path.splitext(value.name)[1]  # [0] returns path+filename
    valid_extensions = ['.jpg', '.png', '.jpeg']
    if not ext.lower() in valid_extensions:
        raise ValidationError(u'Please select a valid image (.jpg,.png,.jpeg)')

class Category(models.Model):
    class Meta:
        verbose_name='Catégorie'
        verbose_name_plural='Catégories'

    title=models.CharField(primary_key=True,max_length=50,null=False,blank=False,verbose_name='Titre')

    def __str__(self):
        return self.title.title()


class Article(models.Model):
    class Meta:
        verbose_name_plural="Articles"

    id=models.AutoField(primary_key=True)
    title=models.CharField(max_length=100,null=False,blank=False,verbose_name="Titre")
    category=models.ForeignKey(Category,null=False,blank=False,verbose_name="Catégorie")
    date=models.DateTimeField(auto_now_add=True)
    content = HTMLField(null=False, blank=False,verbose_name="Contenu")
    resume=models.TextField(null=False,blank=False,verbose_name="Résumé")
    image = models.FileField(validators=[validate_file_extension],verbose_name="Image",blank=True)

    def get_absolute_url(self):
        return resolve('articles:article',kwargs={'pk':self.id})


    def __str__(self):
        return self.title+","+self.category.title

class Comment(models.Model):
    class Meta:
        verbose_name='Commentaire'
        verbose_name_plural="Commentaires"

    id=models.AutoField(primary_key=True)
    article=models.ForeignKey(Article,null=False,blank=False,verbose_name="Article")
    visitor_name=models.CharField(max_length=50,null=False,blank=False,verbose_name="Nom du visiteur")
    commenter_email=models.CharField(max_length=50,null=False,blank=False,verbose_name="Email du visiteur")
    date=models.DateTimeField(auto_now_add=True)
    content=models.TextField(null=False,blank=False,verbose_name="Contenu")

    def __str__(self):
        return self.visitor_name+","+self.content

articles/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.Form):

    class Meta:
        model=Comment
        fields=['visitor_name','visitor_email','content']

    visitor_name = forms.CharField(label='Votre nom', max_length=50,required=True)
    visitor_email = forms.EmailField(label='Votre email', max_length=50,required=True)
    content = forms.CharField(label='Votre commentaire',required=True,max_length=2000,widget=forms.Textarea)

class SearchForm(forms.Form):
    class Meta:
        fields=['keywords']

    keywords=forms.CharField(label='Recherche',max_length=30,required=True)

articles/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.db.models import Q
from .models import Article, Category,Comment
from .forms import CommentForm, SearchForm
from django.db.models import Count
import locale
locale.setlocale(locale.LC_TIME,'')
import time

# Create your views here.

def index(request):

    categories = Category.objects.all()
    last_articles=Article.objects.all().order_by('-date')[:5]
    popular_articles = Article.objects.all().annotate(num_comments=Count('comment')).order_by('-num_comments')[:5]
    posts_per_categories=[]
    for category in categories:
        posts_per_categories.append([category.title,Article.objects.filter(category=category).order_by('-date')[:5]])


    articles = Article.objects.all()
    context = {
        'categories': categories,
        'last_articles':last_articles,
        'posts_per_categories':posts_per_categories,
        'time':time.strftime('%A %d/%m/%Y'),
        'popular_articles':popular_articles
    }
    return render(request, 'index.html', context)


def article(request, article):
    try:
        categories = Category.objects.all()
        last_articles = Article.objects.all().order_by('-date')[:5]
        popular_articles = Article.objects.all().annotate(num_comments=Count('comment')).order_by('-num_comments')[:5]
        article = Article.objects.get(pk=article)
        comments = Comment.objects.filter(article=article)
        if request.method == 'POST':
            form = CommentForm(request.POST)
            if form.is_valid():
                visitor_name=form.cleaned_data['visitor_name']
                visitor_email=form.cleaned_data['visitor_email']
                content=form.cleaned_data['content']
                comment=Comment(article=article,visitor_name=visitor_name,commenter_email=visitor_email,content=content)
                comment.save();
                return HttpResponseRedirect(request.path_info)
        else:
            form = CommentForm()
            context = {
                'article': article,
                'form': form,
                'comments':comments,
                'categories': categories,
                'last_articles': last_articles,
                'popular_articles':popular_articles
                }
            return render(request, 'article.html', context)

    except Article.DoesNotExist:
        raise Http404


def articles(request, category):

    categories = Category.objects.all()
    last_articles = Article.objects.all().order_by('-date')[:5]
    popular_articles = Article.objects.all().annotate(num_comments=Count('comment')).order_by('-num_comments')[:5]
    articles = Article.objects.filter(category=category)
    context = {
        'category':category,
        'articles': articles,
        'categories': categories,
        'last_articles': last_articles,
        'popular_articles':popular_articles
    }
    return render(request, 'articles.html', context)

def search(request):

    categories = Category.objects.all()
    last_articles = Article.objects.all().order_by('-date')[:5]
    popular_articles = Article.objects.all().annotate(num_comments=Count('comment')).order_by('-num_comments')[:5]
    keywords=''

    if request.method=='POST':

        form=SearchForm(request.POST)
        if form.is_valid():
            all_queries = None
            keywords=form.cleaned_data['keywords']
            search_fields = ('title','content','resume')
            for keyword in keywords.split(' '):
                keyword_query = None
                for field in search_fields:
                    each_query = Q(**{field + '__icontains': keyword})
                    if not keyword_query:
                        keyword_query = each_query
                    else:
                        keyword_query = keyword_query | each_query
                        if not all_queries:
                            all_queries = keyword_query
                        else:
                            all_queries = all_queries & keyword_query

            articles = Article.objects.filter(all_queries).distinct()
            context = {
                'keywords':keywords,
                'articles': articles,
                'categories': categories,
                'last_articles': last_articles,
                'popular_articles':popular_articles
            }
            return render(request, 'search.html', context)


    else:

        articles=Article.objects.none()
        context = {
            'keywords': keywords,
            'articles': articles,
            'categories': categories,
            'last_articles': last_articles,
            'popular_articles': popular_articles
        }

        return render(request, 'search.html', context)

articles/templates/article.html
{% extends 'index.html' %}

{% load app_tags %}

{% block title %} {{ article.title }} {% endblock %}

{% block content %}

<div class="col-lg-8">
    <h1 class="mt-4"> {{article.title}}</h1>
    <!-- Date/Time -->
    <p>Posté le {{article.date|date:'d-m-Y H:i'}}, dans {{article.category.title|capitalize }}</p> <hr>
    {% if article.image %}
    <img class="img-fluid" src="{{article.image.url}}">
    {% endif %} <br> <br>
    {{article.content|safe}}
    <!--<a class="fb-share" href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}" target="_blank"> <br> Partager </a> <br> <br>-->
    <a class="fb-share" href="https://www.facebook.com/sharer/sharer.php?u=www.google.com" target="_blank"> <br> Partager </a> <br> <br>
    <h5>Liste des Commentaires</h5> <br>

    {% for comment in comments %}
    <div class="media mb-4">
        <img class="d-flex mr-3 rounded-circle" src="/static/user.png" alt="">
        <div class="media-body">
            <h5 class="mt-0">{{comment.visitor_name}}, le {{comment.date|date:'d-m-Y H:i' }}</h5>
            <div class="post_content">{{comment.content}} </div>
        </div>
    </div>
    {% endfor %}
    <!-- Comments Form -->
    <div class="card my-4">
        <h5 class="card-header">Rédiger un Commentaire</h5>
        <div class="card-body">
            <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" id="id_visitor_name" name="visitor_name" class="form-control" placeholder="Votre nom" required="required">
                    <input type="text" id="id_visitor_email" name="visitor_email" type="email" class="form-control" placeholder="Votre email" required="required">
                    <textarea id="id_content" name="content" class="form-control" rows="3" required="required"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Valider</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

articles/templates/articles.html
{% extends 'index.html' %}
{% load app_tags %}
{% block title %} MyNewsPaper -  {{ category|capitalize }} {% endblock %}

{% block content %}

<div class="col-lg-8">
    <br> <br>
    <h5 class="card-header">Articles dans {{ category.title|capitalize }}</h5> <br>
    {% for article in articles %}
    <div class="card">
        <div class="card-body">
            {% if article.image %}
            <img class="img-fluid" style="height: 250px; width: 100%; display: block;" src="{{article.image.url}}">
            {% endif %} <br> <br>
            <h5 class="card-title">{{article.title}}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{article.date|date:'d-m-Y H:i'}}</h6>
            <p class="card-text">{{article.resume}}</p>
            <a href="{% url 'article' article.id %}" class="card-link">Lire l'article</a>
        </div>
    </div> <br> <br>
    {% endfor %}
</div>


{% endblock %}

articles/templates/index.html
<html>
{% load app_tags %}

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no,user-scalable=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title> {% block title %} Bienvenue à MyNewsPaper {% endblock %} </title>
    <link href="/static/bootstrap/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/bootstrap/css/blog-post.css" rel="stylesheet">
    <link href="/static/style.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
    <link rel="shortcut icon" href="/static/icon.png" />
    <script src="/static/bootstrap/vendor/jquery/jquery.min.js"></script>
    <script src="/static/bootstrap/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script>
        $(document).ready(function()
        {
            $('.fb-share').click(function(e)
            {
                e.preventDefault();
                window.open($(this).attr('href'), 'fbShareWindow', 'height=450, width=550, top=' + ($(window).height() / 2 - 275) + ', left=' + ($(window).width() / 2 - 225) + ', toolbar=0, location=0, menubar=0, directories=0, scrollbars=0');
                return false;
            });
        });
    </script>


  </head>

  <body>


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="site_navbar">
      <div class="container">
        <a class="navbar-brand" id="site_brand" href="/">Bienvenue à MyNewsPaper</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
              {% for category in categories %}
              <li class="nav-item">
              <a class="nav-link" href="/categories/{{category.title}}">{{category.title|capitalize}}</a>
              </li>
              {% endfor %}
          </ul>
        </div>
      </div>
    </nav>


    <div class="container">

      <div class="row">

          <div class="col-md-4">
              <div class="card my-4">
                  <h5 class="card-header">Recherche</h5>
                  <div class="card-body">
                      <div class="input-group">
                          <form action="/search/" method="POST">
                              {% csrf_token %}
                              <input type="text" id="id_keywords" name="keywords" class="form-control" required="required" placeholder="Recherche sur..."><br>
                              <span class="input-group-btn">
                                  <button type="submit" class="btn btn-secondary" type="button">RECHERCHE</button>
                              </span>
                          </form>
                      </div>
                  </div>
              </div>
              <div class="card my-4">
                  <h5 class="card-header">Derniers Articles</h5>
                  <div class="card-body">
                      <div class="row">
                          <ul style="list-style: none;">
                              {% for article in last_articles %}
                              <li> <a href="{% url 'article' article.id %}">{{ article.title }}</a> </li> <br>
                              {% endfor %}
                          </ul>
                      </div>
                  </div>
              </div>

              <div class="card my-4">
                  <h5 class="card-header">Articles Populaires</h5>
                  <div class="card-body">
                      <div class="row">
                          <ul style="list-style: none;">
                              {% for article in popular_articles %}
                              <li> <a href="{% url 'article' article.id %}">{{ article.title }}</a> </li> <br>
                              {% endfor %}
                          </ul>
                      </div>
                  </div>
              </div>

          </div>


          {% block content %}
          <div class="col-lg-8">
              <br>
              <b><h1 class="mt-4" >Le {{time}}</h1></b> <br>
              {% for element in posts_per_categories %}
              <h5 style="cursor:pointer;" class="card-header" data-toggle="collapse" data-target="#{{element.0}}">Articles dans {{element.0|capitalize}}</h5>
              <br> <br>
              <div class="collapse show"  id="{{element.0}}">
                  {% for article in element.1 %}
                  <div class="card">
                      <div class="card-body">
                          {% if article.image %}
                          <img class="img-fluid" src="{{article.image.url}}">
                          {% endif %} <br> <br>
                          <h5 class="card-title">{{article.title}}</h5>
                          <h6 class="card-subtitle mb-2 text-muted">{{article.date|date:'d-m-Y H:i'}}</h6>
                          <p class="card-text">{{article.resume}}</p>
                          <a href="{% url 'article' article.id %}" class="card-link">Lire l'article</a>
                      </div>
                  </div> <br> <br>
                  {% endfor %}
              </div>
              {% endfor %}

          </div>
          {% endblock %}



      </div>


    </div>

    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; MyNewsPaper 2018</p>
      </div>
    </footer>

  </body>

</html>

articles/templates/index_backup.html
<html>
{% load app_tags %}

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no,user-scalable=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title> {% block title %} Bienvenue à MyNewsPaper {% endblock %} </title>
    <link href="/static/bootstrap/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/bootstrap/css/blog-post.css" rel="stylesheet">
    <link href="/static/style.css" rel="stylesheet">
    <link rel="shortcut icon" href="/static/icon.png" />
    <script src="/static/bootstrap/vendor/jquery/jquery.min.js"></script>
    <script src="/static/bootstrap/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script>
        $(document).ready(function()
        {
            $('.fb-share').click(function(e)
            {
                e.preventDefault();
                window.open($(this).attr('href'), 'fbShareWindow', 'height=450, width=550, top=' + ($(window).height() / 2 - 275) + ', left=' + ($(window).width() / 2 - 225) + ', toolbar=0, location=0, menubar=0, directories=0, scrollbars=0');
                return false;
            });
        });
    </script>


  </head>

  <body>


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="site_navbar">
      <div class="container">
        <a class="navbar-brand" id="site_brand" href="/">Bienvenue à MyNewsPaper</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
              {% for category in categories %}
              <li class="nav-item">
              <a class="nav-link" href="/categories/{{category.title}}">{{category.title|capitalize}}</a>
              </li>
              {% endfor %}
          </ul>
        </div>
      </div>
    </nav>


    <div class="container">

      <div class="row">

          {% block content %}
          <div class="col-lg-8">
              <br>
              <b><h1 class="mt-4" >Le {{time}}</h1></b> <br>
              {% for element in posts_per_categories %}
              <h5 style="cursor:pointer;" class="card-header" data-toggle="collapse" data-target="#{{element.0}}">Articles dans {{element.0|capitalize}}</h5>
              <br> <br>
              <div class="collapse show"  id="{{element.0}}">
                  {% for article in element.1 %}
                  <div class="card">
                      <div class="card-body">
                          <table border="0">
                              <tr>
                                  <td width="25%">
                                      {% if article.image %}
                                      <img width="25%" height="70px" src="{{article.image.url}}" alt="">
                                      {% else %}
                                      <img width="25%" height="70px" src="/static/no-fees-icon-B.png" alt="">
                                      {% endif %}
                                  </td>
                                  <td>
                                      <h5 class="card-title">{{article.title}}</h5>
                                      <h6 class="card-subtitle mb-2 text-muted">{{article.date|date:'d-m-Y H:i'}}</h6>
                                      <p class="card-text">{{article.resume}}</p>
                                      <a href="{% url 'article' article.id %}" class="card-link">Afficher tout</a>
                                  </td>
                              </tr>
                          </table>
                      </div>
                  </div> <br> <br>
                  {% endfor %}
              </div>
              {% endfor %}

          </div>
          {% endblock %}

          <div class="col-md-4">
              <div class="card my-4">
                  <h5 class="card-header">Recherche</h5>
                  <div class="card-body">
                      <div class="input-group">
                          <form action="/search/" method="POST">
                              {% csrf_token %}
                              <input type="text" id="id_keywords" name="keywords" class="form-control" required="required" placeholder="Recherche sur..."><br>
                              <span class="input-group-btn">
                                  <button type="submit" class="btn btn-secondary" type="button">RECHERCHE</button>
                              </span>
                          </form>
                      </div>
                  </div>
              </div>
              <div class="card my-4">
                  <h5 class="card-header">Derniers Articles</h5>
                  <div class="card-body">
                      <div class="row">
                          <ul style="list-style: none;">
                              {% for article in last_articles %}
                              <li> <a href="{% url 'article' article.id %}">{{ article.title }}</a> </li>
                              {% endfor %}
                          </ul>
                      </div>
                  </div>
              </div>

              <div class="card my-4">
                  <h5 class="card-header">Articles Populaires</h5>
                  <div class="card-body">
                      <div class="row">
                          <ul style="list-style: none;">
                              {% for article in popular_articles %}
                              <li> <a href="{% url 'article' article.id %}">{{ article.title }}</a> </li>
                              {% endfor %}
                          </ul>
                      </div>
                  </div>
              </div>

          </div>



      </div>


    </div>

    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; MyNewsPaper 2018</p>
      </div>
    </footer>

  </body>

</html>

articles/templates/search.html
{% extends 'index.html' %}

{% block title %} Recherche sur  {{ keywords }} {% endblock %}

{% block content %}

<div class="col-lg-8">
    <br> <h6> Recherche sur  {{ keywords }}  </h6> <br>
    {% for article in articles %}
    <div class="card">
        <div class="card-body">
            {% if article.image %}
            <img class="img-fluid" style="height: 250px; width: 100%; display: block;" src="{{article.image.url}}">
            {% endif %} <br> <br>
            <h5 class="card-title">{{article.title}}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{article.date|date:'d-m-Y H:i'}}</h6>
            <p class="card-text">{{article.resume}}</p>
            <a href="{% url 'article' article.id %}" class="card-link">Lire l'article</a>
        </div>
    </div> <br> <br>
    {% endfor %}
</div>


{% endblock %}